### ISSUE TITLE
Doesn't work in spotify version 

### ISSUE THREAD

**Issue by snoepkast** [dayvson/headphone-bluetooth-spotify#2]
I just installed the app including the 'play button itunes patch' but I still can't control spotify from my headset or from the pop-down menu on the app icon.

Version information:

```
Spotify: 1.0.13.108.gcd94e7db
Mac: 10.10.5 (14F27)
Bluetooth spotify: 1
Headphones: Plantronics BackBeat Pro on firmware 25.0
```

If any more information would be usefull I'm happy to provide.

**Comment by dayvson** [comment]
I will take a look on it today and I'll let you know.

**Comment by snoepkast** [comment]
@dayvson: Great! No worries, it's just a nice to have so there's no rush! If you need any help let me know :)

**Comment by maarten00** [comment]
I've installed it today and noticed it worked out of the box without changing the .plist file. In fact, changing that file caused the app to stop working. 

I'm not sure if the motion sensor pause works though, is it supposed to work with this patch?

**Comment by snoepkast** [comment]
@maarten00 @dayvson: Thanks, I've reverted the .plist file and now it works! Even with the sensors, there's just a little delay (~1s).
